const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  DECREASE_ITEM_QUANTITY: 'DECREASE_ITEM_QUANTITY',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART', 
}

export default CartActionTypes;